---
# handlers file for apache
- name: Restart Apache
  service:
    name: httpd
    state: restarted
  listen: "restart webserver"
- name: Restart Firewall
  service:
    name: firewalld
    state: restarted
  listen: "restart firewall"
