---
- hosts: web
  become: yes
  tasks:
  - name: Check destination directory
    file:
      path: /var/www/html
      state: directory
  - name: Deploy app binary
    copy:
      src: /home/dennis/apps/hello
      dest: /var/www/html/hello
    tags:
      - webdeploy
- hosts: db
  become: yes
  tasks:
  - name: Check destination directory
    file:
      path: /opt/db/scripts
      state: directory
  - name: deploy db script
    copy:
      src: /home/dennis/apps/script.sql
      dest: /opt/db/scripts/script.sql
    tags:
      - dbdeploy
