---
- hosts: centos
  tasks:
    - name: get files
      get_url:
        url: "http://{{ item }}.localdomain:8080/index.html"
        dest: "/tmp/{{ item }}"
      ignore_errors: yes
      with_items:
        - vm-01
        - vm-02
