---
- hosts: localhost
  tasks:
    - name: Download transaction list from http://apps.133t.com
      block:
        - get_url:
            url: http://apps.l33t.com/transaction_list
            dest: /home/ansible/
      rescue:
        - debug: msg="l33t.com appears to be down. Try again later"
      always:
        - debug: msg="Attempt completed"
    - name: "Replace all instances of #BLANKLINE with the lne break character"
      replace:
        path: /home/ansible/transaction_list
        regexp: "#BLANKLINE"
        replace: "\\n"

