---
- hosts: all
  become: yes
  tasks:
    - name: Deploy new sudoers file to servers
      template:
        src: /home/ansible/hardened.j2
        dest: /etc/sudoers.d/hardened
        validate: /sbin/visudo -cf %s

